version: '3.8'
services:
  finance-api:
    build: .
    ports:
      - "8080:8000"
    restart: always
    container_name: finance_api_container
    environment:
      - EUREKA_URL=http://eureka-server:8761
    networks:
      - platform-network

networks:
  platform-network:
    external: true